config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'events#upcoming'

  resources :user_sessions, only: %i[new create] do
    post :delete, on: :collection
  end

  resources :events, only: %i[index update show] do
    get :upcoming, on: :collection
    resources :presents, only: %i[create destroy]
  end

  resources :event_presenters, only: %i[create]
  resources :event_searches, only: %i[create]
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  UPCOMING_MONTHS = 3

  belongs_to :recipient
  belongs_to :event_type
  has_many :presents, dependent: :destroy

  validates :date, presence: true

  scope :upcoming, lambda {
    where(date: Date.current..UPCOMING_MONTHS.months.from_now).order(:date)
  }

  enum state: { pending: 0, purchased: 1, wrapped: 2, gifted: 3 }

  alias_attribute :when, :date

  def who
    recipient.name
  end

  def what
    event_type.name
  end
end

app/models/event_type.rb
# frozen_string_literal: true

class EventType < ApplicationRecord
  has_many :events, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  include Eventable

  before_action :assign_event, only: %i[show update]

  def upcoming
    @events = current_user.events.upcoming
  end

  def index; end

  def show
    @new_present = event.presents.new
  end

  def update
    event.update(event_params)
  end

  private

  attr_reader :event

  def event_params
    params.require(:event).permit(:state)
  end

  def assign_event
    @event = current_user.events.find(params[:id])
  end
end

app/views/events/_actions.html.erb
<%= content_tag(:div, class: 'event-actions') do %>
  <%= content_tag(
    :button,
    t('events.index.search_events'),
    data: {
      action: 'click->show-hide#toggle',
      show_hide_id_param: 'event-search',
      show_hide_target: 'selectable'
    },
    class: "show-hide-button #{'selected' if show_event_search_form}"
  ) %>
  <%= content_tag(
    :button,
    t('events.index.add_event'),
    data: {
      action: 'click->show-hide#toggle',
      show_hide_id_param: 'new-event',
      show_hide_target: 'selectable'
    },
    class: "show-hide-button #{'selected' if show_new_event_form}"
  ) %>
<% end %>

app/views/events/_done.html.erb
<%= simple_form_for(
  event,
  html: {
    data: {
      action: 'change->requests#submitForm'
    }
  }
) do |form| %>
  <%= form.input(
    :state,
    as: :boolean,
    input_html: { checked: event.done? },
    label: false
  ) %>
<% end %>

app/views/events/_edit_state.html.erb
<%= simple_form_for(
  event,
  html: {
    data: {
      action: 'change->requests#submitForm'
    }
  }
) do |form| %>
  <%= form.input(
    :state,
    collection: state_options,
    label: false,
    include_blank: false
  ) %>
<% end %>

app/views/events/_event_table.html.erb
<%= content_tag(:div, class: 'table event-table') do %>
  <%= content_tag(:div, class: 'row') do %>
    <%= content_tag(:div, t('events.show.who'), class: 'cell') %>
    <%= content_tag(:div, event.who, class: 'cell') %>
  <% end %>
  <%= content_tag(:div, class: 'row') do %>
    <%= content_tag(:div, t('events.show.what'), class: 'cell') %>
    <%= content_tag(:div, event.what, class: 'cell') %>
  <% end %>
  <%= content_tag(:div, class: 'row') do %>
    <%= content_tag(:div, t('events.show.when'), class: 'cell') %>
    <%= content_tag(:div, display_date(event.when), class: 'cell') %>
  <% end %>
  <%= content_tag(:div, class: 'row') do %>
    <%= content_tag(:div, t('events.show.recurring'), class: 'cell') %>
    <%= content_tag(:i, nil, class: boolean_icon_class(event.recurring)) %>
  <% end %>
  <%= content_tag(:div, class: 'row') do %>
    <%= content_tag(:div, t('events.show.state'), class: 'cell') %>
    <%= content_tag(:div, class: 'cell') do %>
      <%= render(partial: 'events/edit_state', locals: { event: event }) %>
    <% end %>
  <% end %>
<% end %>

app/views/events/_events_table.html.erb
<%= content_tag(:div, class: 'table') do %>
  <% events.each do |event| %>
    <%= link_to(event_path(event), class: 'row') do %>
      <%= content_tag(:div, event.who, class: 'cell') %>
      <%= content_tag(:div, event.what, class: 'cell') %>
      <%= content_tag(:div, display_date(event.when), class: 'cell') %>
      <%= content_tag(:div, class: 'cell') do %>
        <%= content_tag(:i, nil, class: state_icon_class(event.state)) %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/events/_new.html.erb
<%= content_tag(
  :div,
  data: { show_hide_target: 'toggleable' },
  class: "show-hide-section #{'hidden' if hidden}",
  id: 'new-event'
) do %>
  <%= render(partial: 'events/form', locals: { event: new_event }) %>
<% end %>

app/views/events/index.html.erb
<%= content_tag(:h1, t('.title')) %>
<%= content_tag(
  :div,
  data: { controller: 'show-hide' },
  class: 'event-management'
) do %>
  <%= render(
    partial: 'events/actions',
    locals: {
      show_event_search_form: @show_event_search_form,
      show_new_event_form: @show_new_event_form
    }
  ) %>
  <%= render(
    partial: 'event_searches/new',
    locals: { event_search: @event_search, hidden: !@show_event_search_form}
  ) %>
  <%= render(
    partial: 'event_presenters/new',
    locals: {
      new_event_presenter: @new_event_presenter,
      hidden: !@show_new_event_form
    }
  ) %>
<%end %>
<%= render(partial: 'events/events_table', locals: { events: @events }) %>

app/views/events/show.html.erb
<%= content_tag(:h1, t('.title')) %>
<%= render(partial: 'events/event_table', locals: { event: @event }) %>
<%= content_tag(:h2, t('.presents')) %>
<%= render(
  partial: 'presents/table',
  locals: { event: @event, presents: @event.presents.all }
) %>
<%= render(
  partial: 'presents/form',
  locals: { event: @event, present: @new_present }
) %>

app/views/events/upcoming.html.erb
<%= content_tag(:h1, t('.title')) %>
<%= render(partial: 'events_table', locals: { events: @events }) %>