config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'events#upcoming'

  resources :user_sessions, only: %i[new create] do
    post :delete, on: :collection
  end

  resources :events, only: %i[index update show] do
    get :upcoming, on: :collection
    resources :presents, only: %i[create destroy]
  end

  resources :event_presenters, only: %i[create]
  resources :event_searches, only: %i[create]
end

app/views/layouts/_nav_bar.html.erb
<%= content_tag(:div, class: 'nav-bar') do %>
  <% if current_user.present? %>
    <%= link_to(t('.upcoming_events'), upcoming_events_path, class: 'nav-item') %>
    <%= link_to(t('.events'), events_path, class: 'nav-item') %>
    <%= button_to(
      t('.log_out'),
      delete_user_sessions_path,
      class: 'nav-item'
    ) %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Presents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Kurenaido&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e81d5e4e5a.js" crossorigin="anonymous"></script>
  </head>
  <%= content_tag(:body, data: { controller: 'requests' }) do %>
    <%= render(partial: 'layouts/nav_bar') %>
    <%= content_tag(:main, yield, data: { controller: 'focus' }) %>
  <% end %>
</html>